import type { Metadata } from "next";
import { Cormorant, Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Toaster } from "sonner";

const manrope = Manrope({
  variable: "--manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PerfumeStore | Products",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <Header />
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
